; DEFINICION DEL SEGMENTO DE DATOS
    DATOS SEGMENT 
        VIVA_SBM DB 0 
	    TOME DW 0CAFEH
	    TABLA300 DB 300 DUP(0)
	    ERRORFATAL2 DB,"[20;ESTE PROGRAMA SE CUELGA SIEMPRE."
    DATOS ENDS

; DEFINICION DEL SEGMENTO DE PILA
    PILA SEGMENT STACK "STACK"
        DB 40H DUP (0) ;ejemplo de inicialización, 64 bytes inicializados a 0
    PILA ENDS

; DEFINICION DEL SEGMENTO EXTRA
    EXTRA SEGMENT
        RESULT DW 0,0 ;ejemplo de inicialización. 2 PALABRAS (4 BYTES) 
    EXTRA ENDS

; DEFINICION DEL SEGºMENTO DE CODIGO
    CODE SEGMENT
        ASSUME CS: CODE, DS: DATOS, ES: EXTRA, SS: PILA
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
    INICIO PROC
; INICIALIZA LOS REGISTROS DE SEGMENTO CON SU VALOR
    MOV AX, DATOS
    MOV DS, AX
    MOV AX, PILA
    MOV SS, AX
    MOV AX, EXTRA
    MOV ES, AX
    MOV SP, 64 ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO
    ; FIN DE LAS INICIALIZACIONES
    ; COMIENZO DEL PROGRAMA 

	MOV AL, ERRORFATAL2[02H]
	MOV TABLA300[62H], AL
	
	MOV SI, 03H
	MOV DI, 0H

	MOV AL, BYTE PTR TOME[DI]
	MOV TABLA300[SI], AL
	
	MOV AL, BYTE PTR TOME+1
	MOV VIVA_SBM, AL

; FIN DEL PROGRAMA
MOV AX, 4C00H
INT 21H
INICIO ENDP
; FIN DEL SEGMENTO DE CODIGO
CODE ENDS
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO