; Sergio Hidalgo 
; DEFINICION DEL SEGMENTO DE DATOS
    DATOS SEGMENT 
		CLR_PANT DB 1BH,"[2","J$"
		TABLA9 DW 9 DUP(0)
		OPCION1	DB 	1BH,"[4; 1) Calcular el determinante con valores por defecto",'$'
		OPCION2	DB 	1BH,"[16; 2) Calcular el determinante con valores introducidos por teclado",'$'
		SALTO DB 1BH, "[30", 0DH, 0AH, '$'
		SELECCION DB 1BH,"[10", '$'

		; SELECCION DB 
    DATOS ENDS
; DEFINICION DEL SEGMENTO DE PILA
    PILA SEGMENT STACK "STACK"
        DB 40H DUP (0) ;ejemplo de inicialización, 64 bytes inicializados a 0
    PILA ENDS

; DEFINICION DEL SEGMENTO EXTRA
    EXTRA SEGMENT
        RESULT DW 0,0 ;ejemplo de inicialización. 2 PALABRAS (4 BYTES)
    EXTRA ENDS

; DEFINICION DEL SEGMENTO DE CODIGO
    CODE SEGMENT
        ASSUME CS: CODE, DS: DATOS, ES: EXTRA, SS: PILA
; COMIENZO DEL PROCEDIMIENTO PRINCIPAL
    INICIO PROC
; INICIALIZA LOS REGISTROS DE SEGMENTO CON SU VALOR
    MOV AX, DATOS
    MOV DS, AX
    MOV AX, PILA
    MOV SS, AX
    MOV AX, EXTRA
    MOV ES, AX
    MOV SP, 64 ; CARGA EL PUNTERO DE PILA CON EL VALOR MAS ALTO
; FIN DE LAS INICIALIZACIONES
; COMIENZO DEL PROGRAMA


	MOV AH,9	
	MOV DX, OFFSET CLR_PANT
	INT 21H

rein:
	MOV DX,OFFSET OPCION1		
	INT 21H
	
	MOV DX,OFFSET SALTO		
	INT 21H
	
	MOV DX ,OFFSET OPCION2	
	INT 21H
	
	MOV DX,OFFSET SALTO		
	INT 21H
	
	MOV AH, 0AH			
	MOV DX, OFFSET SELECCION
	MOV SELECCION[1], 20
	INT 21H
	
	
	MOV AH,9	
	MOV DX, OFFSET CLR_PANT
	INT 21H
	
	mov ax, OFFSET SELECCION
	mov bx, '1'
	
	
	cmp ax, bx
	je etiq1
	
	mov bx, '2'
	
	
	cmp ax, bx
	je etiq2

	jmp rein
	
	

	
	
	
	
	
etiq1:	
	
	MOV DX,OFFSET OPCION1		
	INT 21H
	
etiq2:	

	MOV DX ,OFFSET OPCION2	
	INT 21H
	
	
; FIN DEL PROGRAMA
MOV AX, 4C00H
INT 21H
INICIO ENDP
; FIN DEL SEGMENTO DE CODIGO
CODE ENDS
; FIN DEL PROGRAMA INDICANDO DONDE COMIENZA LA EJECUCION
END INICIO