#ifndef OBJECT_TEST_H
#define OBJECT_TEST_H

#include <stdio.h>

void test1_object_create();
void test2_object_create();
void test3_object_create();
void test1_object_setDescription();
void test2_object_setDescription();
void test3_object_setDescription();
void test1_object_set_name();
void test2_object_set_name();
void test3_object_set_name();
void test1_object_get_id();
void test2_object_get_id();
void test1_object_getDescription();
void test2_object_getDescription();
void test1_object_get_name();
void test2_object_get_name();
void test1_object_Idcheck();
void test2_object_IdCheck();
void test3_object_IdCheck();
void test1_object_set_movable();
void test2_object_set_movable();
void test3_object_set_movable();
void test1_object_get_movable();
void test2_object_get_movable();
void test1_object_set_dependency();
void test2_object_set_dependency();
void test3_object_set_dependency();
void test1_object_get_dependency();
void test2_object_get_dependency();
void test1_object_set_open();
void test2_object_set_open();
void test3_object_set_open();
void test1_object_get_open();
void test2_object_get_open();
void test1_object_set_illuminate();
void test2_object_set_illuminate();
void test1_object_get_illuminate();
void test2_object_get_illuminate();
void test1_object_set_turnedon();
void test2_object_set_turnedon();
void test1_object_get_turnedon();
void test2_object_get_turnedon();

#endif /*OBJECT_TEST_H*/