# Generated by Django 3.2.1 on 2023-05-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20230508_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fechaDeSuscripcion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
