# Generated by Django 4.2.1 on 2023-05-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoSuperficie', models.CharField(max_length=100)),
                ('enMantenimiento', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreSocio', models.CharField(max_length=100)),
                ('fechaDeSuscripcion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateField(auto_now_add=True)),
                ('horaReserva', models.DateTimeField(auto_now_add=True)),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.pista')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.socio')),
            ],
        ),
    ]
