# Generated by Django 3.2.1 on 2023-05-07 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCanal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeSuscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.usuario')),
            ],
        ),
    ]
