# Generated by Django 3.2.1 on 2023-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_suscripcion_fechadesuscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='fechaDeSuscripcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
